const allSkins = [
  {
    id: 1,
    name: 'AK-47 | Case Hardened',
    weapon: 'AK-47',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLwlcK3wiNK0P2nZKFpH_yaCW-Ej7sk5bE8Sn-2lEpz4zndzoyvdHuUPwFzWZYiE7EK4Bi4k9TlY-y24FbAy9USGSiZd5Q',
    price: 25000,
    rarity: 'Засекреченное',
    float: 0.07,
    wear: 'Minimal Wear',
    seed: 661,
    stattrak: true,
    description: 'Редкий паттерн с высоким содержанием синего — настоящий collector-grade вариант для любителей Case Hardened.'
  },
  {
    id: 2,
    name: 'AWP | Dragon Lore',
    weapon: 'AWP',
    image: 'https://skins-cdn.hltv.org/skin/Cyz4AWdqXht6NWHlj9sWtl.png',
    price: 42000,
    rarity: 'Тайное',
    float: 0.12,
    wear: 'Minimal Wear',
    seed: 250,
    stattrak: false,
    description: 'Легендарный дизайн, редкий рисунок и сильная ценность на рынке — один из самых узнаваемых скинов в CS2.'
  },
  {
    id: 3,
    name: 'M4A1-S | Golden Coil',
    weapon: 'M4A1-S',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8ypexwjFS4_ega6F_H_eAMWrEwL9lj_JnTiK2lxQztgKClYP9HifOOV5kFJclQ-Jb5xW-m9CxPuLq4QTfjd0XzyX6jCpL6X5o5OgDVfYn_a2Ci1rfcepqgV49FrE',
    price: 18000,
    rarity: 'Тайное',
    float: 0.21,
    wear: 'Field-Tested',
    seed: 148,
    stattrak: true,
    description: 'Изысканный золотой оттенок в сочетании с аккуратным износом делает этот скин особенно выгодным для коллекции.'
  },
  {
    id: 4,
    name: 'Glock-18 | Fade',
    weapon: 'Glock-18',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL2kpnj9h1a7s2oaaBoH_yaCW-Ej-8u5bZvHnq1w0Vz62TUzNj4eCiVblMmXMAkROJeskLpkdXjMrzksVTAy9US8PY25So',
    price: 9400,
    rarity: 'Запрещённое',
    float: 0.05,
    wear: 'Factory New',
    seed: 441,
    stattrak: false,
    description: 'Плавный градиент и идеальное состояние делают этот вариант популярным среди коллекционеров.'
  },
  {
    id: 5,
    name: 'USP-S | Kill Confirmed',
    weapon: 'USP-S',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLkjYbf7itX6vytbbZSI-WsG3SA_uV_vO1WTCa9kxQ1vjiBpYPwJiPTcFB2Xpp5TO5cskG9lYCxZu_jsVCL3o4Xnij23ClO5ik9tegFA_It8qHJz1aWe-uc160',
    price: 6200,
    rarity: 'Тайное',
    float: 0.27,
    wear: 'Field-Tested',
    seed: 812,
    stattrak: true,
    description: 'Сбалансированный бюджетный скин с аккуратным рисунком и хорошим потенциалом для лоу-бюджетной сборки.'
  },
  {
    id: 6,
    name: 'Desert Eagle | Blaze',
    weapon: 'Desert Eagle',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL1m5fn8Sdk7vORbqhsLfWAMWuZxuZi_uI_TX6wxxkjsGXXnImsJ37COlUoWcByEOMOtxa5kdXmNu3htVPZjN1bjXKpkHLRfQU',
    price: 12000,
    rarity: 'Запрещённое',
    float: 0.14,
    wear: 'Minimal Wear',
    seed: 504,
    stattrak: false,
    description: 'Яркая огненная палитра и укороченная смесь тёплых тонов делают этот скин заметным в любой партии.'
  },
  {
    id: 7,
    name: 'MP9 | Hydra',
    weapon: 'MP9',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8js_f_jdk4uL3V6x0JOKSMWuZxuZi_rQ9H363xU5_4GrWnIr8IHqfbwBxA5R2QuZZshm6kdO2Mum35Q3ajoJbjXKp1xQlWoY',
    price: 15500,
    rarity: 'Засекреченное',
    float: 0.35,
    wear: 'Field-Tested',
    seed: 668,
    stattrak: true,
    description: 'Гидра в дизайне, дерзкая цветовая схема и плотная детализация рисунка подчеркивают уникальность.'
  },
  {
    id: 8,
    name: 'MAC-10 | Neon Rider',
    weapon: 'MAC-10',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8n5WxrR1Y-s2jaac8cM-dC2ie0-dytfNWQyC0nQlp5DzTntmgdC7COABxX5NxQrUOtUS5w4LgMu6zsVCK2IJCmyisjitM6DErvbicsEA0SQ',
    price: 8700,
    rarity: 'Тайное',
    float: 0.58,
    wear: 'Well-Worn',
    seed: 935,
    stattrak: false,
    description: 'Яркая неоновая энергия в минималистичной геометрии и среднее состояние износа для эффектного вида.'
  },
  {
    id: 9,
    name: 'FAMAS | Mecha Industries',
    weapon: 'FAMAS',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL3n5vh7h1c_M2oaalsM8-eC2SYwNF6ueZhW2ewwx4hsm3dz46heSjCPVUjC8chEOYMtxOwkNHiYb63swXY3Y9Nn32skGoXuc3DGOrc',
    price: 4100,
    rarity: 'Засекреченное',
    float: 0.81,
    wear: 'Battle-Scarred',
    seed: 120,
    stattrak: false,
    description: 'Выносливый и доступный скин для игроков, которым важен баланс цены и комфорта в игре.'
  },
  {
    id: 10,
    name: 'Galil AR | Sandstorm',
    weapon: 'Galil AR',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL2n5rp8SNJ0PG7V7dsLvSAGmiCzNF6ueZhW2exkx4m6mrcmd6heS-XZgB1ApZ3FLUI5xm6ktezMuzh7gTeiYpFnCr-kGoXuTw2UKiI',
    price: 5600,
    rarity: 'Промышленное качество',
    float: 0.49,
    wear: 'Well-Worn',
    seed: 217,
    stattrak: true,
    description: 'Обволакивающая песчаная палитра и эффект легкой потертости делают скин максимально универсальным.'
  },
  {
    id: 11,
    name: 'M4A4 | The Coalition',
    weapon: 'M4A4',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8ypexwiVI0P_6afBSI_-SAm6EyOF4j-1gSCGn200jt2_XnIuseX_GaFR0XpEhReULtUKxlIWzP-_gs1HZjI1NzSutiClXrnE8e4r3Ge8',
    price: 11200,
    rarity: 'Тайное',
    float: 0.18,
    wear: 'Field-Tested',
    seed: 777,
    stattrak: false,
    description: 'Классическая модель с жесткой и лаконичной стилистикой — отличный вариант для сбалансированного набора.'
  },
  {
    id: 12,
    name: 'AK-47 | Redline',
    weapon: 'AK-47',
    image: 'https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_ak47_cu_ak47_cobra_light_large.7494bfdf4855fd4e6a2dbd983ed0a243c80ef830.png',
    price: 14800,
    rarity: 'Засекреченное',
    float: 0.31,
    wear: 'Field-Tested',
    seed: 472,
    stattrak: true,
    description: 'Сдержанная, но сильная красная подсветка и аккуратный рисунок для тех, кто любит агрессивный стиль.'
  },
  {
    id: 13,
    name: 'AWP | Asiimov',
    weapon: 'AWP',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLwiYbf_jdk7uW-V6V-Kf2cGFidxOp_pewnF3nhxEt0sGnSzN76dH3GOg9xC8FyEORftRe-x9PuYurq71bW3d8UnjK-0H0YSTpMGQ',
    price: 19600,
    rarity: 'Тайное',
    float: 0.09,
    wear: 'Minimal Wear',
    seed: 304,
    stattrak: false,
    description: 'Легендарный бело-оранжевый дизайн с сильным визуальным эффектом и высокой ликвидностью на рынке.'
  },
  {
    id: 14,
    name: 'Nomad Knife | Fade',
    weapon: 'Нож',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL6kJ_m-B1U-uaqZ6t_H_GSMWGRxetJvOhuRz39wUUksW7Vm4n7d3yUO1InXsdxTeQDukO4l9zuN7_j5QzYjIlFy3n6jDQJsHjNMoy1vA',
    price: 21800,
    rarity: 'Редкое спецпредложение',
    float: 0.04,
    wear: 'Factory New',
    seed: 921,
    stattrak: false,
    description: 'Нож с плавным градиентом и высоким уровнем эстетики в стиле дорогой коллекционной подачи.'
  },
  {
    id: 15,
    name: 'Sport Gloves | Vice',
    weapon: 'Перчатки',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Tk5UvzWCL2kpn2-DFk_OKherB0H_KfG2Kv0ed4u95lRi67gVNx4T-Bw434IHyVb1QlAsd1FOUDthG4xNznMu3m4QXXg90Wzn_33C1I8G81tLaDi_rK',
    price: 7800,
    rarity: 'Редкое спецпредложение',
    float: 0.23,
    wear: 'Field-Tested',
    seed: 101,
    stattrak: false,
    description: 'Элегантный спортивный набор для тех, кто ценит минимализм, тактильность и сильный визуальный акцент.'
  },
  {
    id: 16,
    name: 'M4A1-S | Hyper Beast',
    weapon: 'M4A1-S',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL8ypexwjFS4_ega6F_H_OGMWrEwL9JuPh5SjuMlxgmoCm6lob-KT-JbwF1WZEjR-YJskK9k9XiYePltAeNjYlAxSn5j34dvCZstb4LB6Ut-7qX0V8Xkv5_2A',
    price: 23300,
    rarity: 'Тайное',
    float: 0.11,
    wear: 'Minimal Wear',
    seed: 559,
    stattrak: true,
    description: 'Дикий и необычный мега-рисунок с агрессивным набором цветов и сильным профилем коллекционера.'
  },
  {
    id: 17,
    name: 'USP-S | Night Ops',
    weapon: 'USP-S',
    image: 'https://skins-cdn.hltv.org/skin/z0ekJzOomm4mkt1EYkQ7kd.png',
    price: 2800,
    rarity: 'Ширпотреб',
    float: 0.66,
    wear: 'Battle-Scarred',
    seed: 357,
    stattrak: false,
    description: 'Лёгкая адаптация для эконом-моделей с достойным визуальным результатом и простой структурой.'
  },
  {
    id: 18,
    name: 'P250 | Ironclad',
    weapon: 'P250',
    image: 'https://steamcdn-a.akamaihd.net/apps/730/icons/econ/default_generated/weapon_p250_gs_p250_metal_panels_light_large.a104ce12e50fa24711708782e5d7b23e1bcb7d1b.png',
    price: 6400,
    rarity: 'Промышленное качество',
    float: 0.44,
    wear: 'Well-Worn',
    seed: 46,
    stattrak: false,
    description: 'Надёжный и крепкий скин с сильным визуальным контрастом и аккуратной полировкой поверхности.'
  },
  {
    id: 19,
    name: 'Glock-18 | Water Elemental',
    weapon: 'Glock-18',
    image: 'https://community.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyL2kpnj9h1Y-s2pZKtuK72fB3aFxP11te99cCW6khUz_TjVyompc3-QOFR2DJQkFOMJtBbqk9LlY-7n5QLZjtkTxCWqhixPv311o7FVIf8eASQ',
    price: 9300,
    rarity: 'Засекреченное',
    float: 0.26,
    wear: 'Field-Tested',
    seed: 191,
    stattrak: true,
    description: 'Мягкий эффект воды и чёткая геометрия делают этот вариант особенно привлекательным для компромисса.'
  },
  {
    id: 20,
    name: 'M9 Bayonet | Gamma-Doppler',
    weapon: 'Нож',
    image: 'https://community.akamai.steamstatic.com/economy/image/-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpovbSsLQJf3qr3czxb49KzgL-KmsjxPr7Dl2dV18hwmOvN8IXvjVCLpxo7Oy3tIYKVIVNtYFjS_FC2yLvogMK4vM7NmHQ36CMgsHfbmhHkh0tEO-dtg-veFwv998pqQw',
    price: 26500,
    rarity: 'Редкое спецпредложение',
    float: 0.08,
    wear: 'Minimal Wear',
    seed: 842,
    stattrak: true,
    description: 'Дорогостоящий нож с эффектом плавного спектра и высокой коллекционной ценностью для редких наборов.'
  }
];

const rarityColors = {
  'Ширпотреб': '#ffffff',
  'Промышленное качество': '#6bbefc',
  'Армейское качество': '#1f4fce',
  'Запрещённое': '#ab67ff',
  'Засекреченное': '#ff78d3',
  'Тайное': '#ff3d47',
  'Редкое спецпредложение': '#f4d35e'
};

const defaultSaleSkins = [
  {
    id: 'custom-1',
    name: 'AK-47 | Neon Rider',
    weapon: 'AK-47',
    image: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGIGz3UqlXOLrxM-vMGmW8VNxu5Dx60noTyLwlcK3wiFO0POlV6poL_6sHG6UxPxJvOhuRz39xkQhsTnVzoygdy7Ea1UoCZQkRe9bs0brl9TvN-m0tVHYjY5CyS35jjQJsHhk4o5zcA',
    price: 8400,
    rarity: 'Тайное',
    float: 0.12,
    wear: 'Minimal Wear',
    seed: 449,
    stattrak: true,
    description: 'Пользовательский скин с неоновым акцентом и выразительным дизайном.'
  }
];
