const allSkins = [
  {
    id: 1,
    name: 'AK-47 | Case Hardened',
    weapon: 'AK-47',
    image: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?auto=format&fit=crop&w=900&q=80',
    price: 25000,
    rarity: 'Запрещённое',
    float: 0.07,
    wear: 'Minimal Wear',
    seed: 661,
    stattrak: true,
    description: 'Редкий паттерн с высоким содержанием синего — настоящий collector-grade вариант для любителей Case Hardened.'
  },
  {
    id: 2,
    name: 'AWP | Dragon Lore',
    weapon: 'AWP',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80',
    price: 42000,
    rarity: 'Тайное',
    float: 0.12,
    wear: 'Minimal Wear',
    seed: 250,
    stattrak: false,
    description: 'Легендарный дизайн, редкий рисунок и сильная ценность на рынке — один из самых узнаваемых скинов в CS2.'
  },
  {
    id: 3,
    name: 'M4A1-S | Golden Coil',
    weapon: 'M4A1-S',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80',
    price: 18000,
    rarity: 'Засекреченное',
    float: 0.21,
    wear: 'Field-Tested',
    seed: 148,
    stattrak: true,
    description: 'Изысканный золотой оттенок в сочетании с аккуратным износом делает этот скин особенно выгодным для коллекции.'
  },
  {
    id: 4,
    name: 'Glock-18 | Fade',
    weapon: 'Glock-18',
    image: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?auto=format&fit=crop&w=900&q=80',
    price: 9400,
    rarity: 'Запрещённое',
    float: 0.05,
    wear: 'Factory New',
    seed: 441,
    stattrak: false,
    description: 'Плавный градиент и идеальное состояние делают этот вариант популярным среди коллекционеров.'
  },
  {
    id: 5,
    name: 'USP-S | Kill Confirmed',
    weapon: 'USP-S',
    image: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=900&q=80',
    price: 6200,
    rarity: 'Армейское качество',
    float: 0.27,
    wear: 'Field-Tested',
    seed: 812,
    stattrak: true,
    description: 'Сбалансированный бюджетный скин с аккуратным рисунком и хорошим потенциалом для лоу-бюджетной сборки.'
  },
  {
    id: 6,
    name: 'Desert Eagle | Blaze',
    weapon: 'Desert Eagle',
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=900&q=80',
    price: 12000,
    rarity: 'Засекреченное',
    float: 0.14,
    wear: 'Minimal Wear',
    seed: 504,
    stattrak: false,
    description: 'Яркая огненная палитра и укороченная смесь тёплых тонов делают этот скин заметным в любой партии.'
  },
  {
    id: 7,
    name: 'MP9 | Hydra',
    weapon: 'MP9',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
    price: 15500,
    rarity: 'Запрещённое',
    float: 0.35,
    wear: 'Field-Tested',
    seed: 668,
    stattrak: true,
    description: 'Гидра в дизайне, дерзкая цветовая схема и плотная детализация рисунка подчеркивают уникальность.'
  },
  {
    id: 8,
    name: 'MAC-10 | Neon Rider',
    weapon: 'MAC-10',
    image: 'https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=900&q=80',
    price: 8700,
    rarity: 'Промышленное качество',
    float: 0.58,
    wear: 'Well-Worn',
    seed: 935,
    stattrak: false,
    description: 'Яркая неоновая энергия в минималистичной геометрии и среднее состояние износа для эффектного вида.'
  },
  {
    id: 9,
    name: 'FAMAS | Mecha Industries',
    weapon: 'FAMAS',
    image: 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?auto=format&fit=crop&w=900&q=80',
    price: 4100,
    rarity: 'Ширпотреб',
    float: 0.81,
    wear: 'Battle-Scarred',
    seed: 120,
    stattrak: false,
    description: 'Выносливый и доступный скин для игроков, которым важен баланс цены и комфорта в игре.'
  },
  {
    id: 10,
    name: 'Galil AR | Sandstorm',
    weapon: 'Galil AR',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
    price: 5600,
    rarity: 'Промышленное качество',
    float: 0.49,
    wear: 'Well-Worn',
    seed: 217,
    stattrak: true,
    description: 'Обволакивающая песчаная палитра и эффект легкой потертости делают скин максимально универсальным.'
  },
  {
    id: 11,
    name: 'M4A4 | The Coalition',
    weapon: 'M4A4',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80',
    price: 11200,
    rarity: 'Армейское качество',
    float: 0.18,
    wear: 'Field-Tested',
    seed: 777,
    stattrak: false,
    description: 'Классическая модель с жесткой и лаконичной стилистикой — отличный вариант для сбалансированного набора.'
  },
  {
    id: 12,
    name: 'AK-47 | Redline',
    weapon: 'AK-47',
    image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=900&q=80',
    price: 14800,
    rarity: 'Запрещённое',
    float: 0.31,
    wear: 'Field-Tested',
    seed: 472,
    stattrak: true,
    description: 'Сдержанная, но сильная красная подсветка и аккуратный рисунок для тех, кто любит агрессивный стиль.'
  },
  {
    id: 13,
    name: 'AWP | Asiimov',
    weapon: 'AWP',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80',
    price: 19600,
    rarity: 'Тайное',
    float: 0.09,
    wear: 'Minimal Wear',
    seed: 304,
    stattrak: false,
    description: 'Легендарный бело-оранжевый дизайн с сильным визуальным эффектом и высокой ликвидностью на рынке.'
  },
  {
    id: 14,
    name: 'Nomad Knife | Fade',
    weapon: 'Нож',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=900&q=80',
    price: 21800,
    rarity: 'Редкое спецпредложение',
    float: 0.04,
    wear: 'Factory New',
    seed: 921,
    stattrak: false,
    description: 'Нож с плавным градиентом и высоким уровнем эстетики в стиле дорогой коллекционной подачи.'
  },
  {
    id: 15,
    name: 'Sport Gloves | Vice',
    weapon: 'Перчатки',
    image: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&w=900&q=80',
    price: 7800,
    rarity: 'Засекреченное',
    float: 0.23,
    wear: 'Field-Tested',
    seed: 101,
    stattrak: false,
    description: 'Элегантный спортивный набор для тех, кто ценит минимализм, тактильность и сильный визуальный акцент.'
  },
  {
    id: 16,
    name: 'M4A1-S | Hyper Beast',
    weapon: 'M4A1-S',
    image: 'https://images.unsplash.com/photo-1523633589114-88eaf4b4f1a8?auto=format&fit=crop&w=900&q=80',
    price: 23300,
    rarity: 'Тайное',
    float: 0.11,
    wear: 'Minimal Wear',
    seed: 559,
    stattrak: true,
    description: 'Дикий и необычный мега-рисунок с агрессивным набором цветов и сильным профилем коллекционера.'
  },
  {
    id: 17,
    name: 'USP-S | Night Ops',
    weapon: 'USP-S',
    image: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=900&q=80',
    price: 2800,
    rarity: 'Ширпотреб',
    float: 0.66,
    wear: 'Battle-Scarred',
    seed: 357,
    stattrak: false,
    description: 'Лёгкая адаптация для эконом-моделей с достойным визуальным результатом и простой структурой.'
  },
  {
    id: 18,
    name: 'P250 | Ironclad',
    weapon: 'P250',
    image: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=900&q=80',
    price: 6400,
    rarity: 'Промышленное качество',
    float: 0.44,
    wear: 'Well-Worn',
    seed: 46,
    stattrak: false,
    description: 'Надёжный и крепкий скин с сильным визуальным контрастом и аккуратной полировкой поверхности.'
  },
  {
    id: 19,
    name: 'Glock-18 | Water Elemental',
    weapon: 'Glock-18',
    image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=80',
    price: 9300,
    rarity: 'Армейское качество',
    float: 0.26,
    wear: 'Field-Tested',
    seed: 191,
    stattrak: true,
    description: 'Мягкий эффект воды и чёткая геометрия делают этот вариант особенно привлекательным для компромисса.'
  },
  {
    id: 20,
    name: 'M9 Bayonet | Doppler',
    weapon: 'Нож',
    image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=900&q=80',
    price: 26500,
    rarity: 'Редкое спецпредложение',
    float: 0.08,
    wear: 'Minimal Wear',
    seed: 842,
    stattrak: true,
    description: 'Дорогостоящий нож с эффектом плавного спектра и высокой коллекционной ценностью для редких наборов.'
  }
];

const rarityColors = {
  'Ширпотреб': '#ffffff',
  'Промышленное качество': '#6bbefc',
  'Армейское качество': '#1f4fce',
  'Запрещённое': '#ab67ff',
  'Засекреченное': '#ff78d3',
  'Тайное': '#ff3d47',
  'Редкое спецпредложение': '#f4d35e'
};

const defaultSaleSkins = [
  {
    id: 'custom-1',
    name: 'AK-47 | Neon Rider',
    weapon: 'AK-47',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80',
    price: 8400,
    rarity: 'Запрещённое',
    float: 0.12,
    wear: 'Minimal Wear',
    seed: 449,
    stattrak: true,
    description: 'Пользовательский скин с неоновым акцентом и выразительным дизайном.'
  }
];
